### PR TITLE
Rewritten addRandomTile() to return game over in case no tiles can be added

### PR DESCRIPTION
**Pull request by Merijn-DH**
I think this should work

### CODE REVIEW

**Comment by jvnknvlgl** [comment]
Note that sometimes even if no tile can be added it might be possible to continue the game because some tiles can be added together still.

**Comment by Merijn-DH** [comment]
`addRandomTile()` is always called after a swipe, it that swipe does ANYTHING there is always an empty spot afterwards.

**Comment by jvnknvlgl** [comment]
NameError: name 'col' is not defined

**Comment by Merijn-DH** [comment]
ok hold on, installing python3

**Pull request merged**
